TRUNCATE TABLE comments RESTART IDENTITY CASCADE;
TRUNCATE TABLE post RESTART IDENTITY CASCADE;
TRUNCATE TABLE post_likes RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE users_roles RESTART IDENTITY CASCADE;